<a href="https://colab.research.google.com/github/frosol11/dataanalystum/blob/main/CDAP_T2_from_scripts_to_structured_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/ERA-Software/computational-data-analysis/blob/main/notebooks/T2_from_scripts_to_structured_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Data Analysis with Python - Week 2** 🔍 📊 🐍

## 📌 Overview
This second week tutorial closes the introductory part to Python coding. You will go through these topics: libraries, functions, OOP and files management. Each part contains exercises you must solve to understand deeply the concepts around advanced data structures in Python and then to apply them to the Hackathon.


### 🧠 **Learning objectives**
- Importing basic Libraries and exploiting their functionalities
- Understanding the basic concepts of functions and applying them to improve readability of your code
- Using Gemini consciously, how to prompt and how to debug improper prompting

### 🐍 **New in Python**
- pip
- Libraries
- Functions
- Classes and OOP
- Files

### 1. Libraries
- **1.1. Library**
- **1.2. pip - Python Package Manager**

### 2. Functions
- **2.1. Syntax**
- **2.2. High-order function**
- **2.3. Anonymous function**

### 3. Classes and OOP

### 4. Files

### 5. Hackaton: the grocery warehouse Pt.2📦

## 1. **Libraries**
Some very smart people built lower level pieces of code that High-IQ people can exploit for their own purposes (This is us), and remember: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it."
— **Attributed to Bill Gates**

So, let's trust the scientific research and go on with our tutorial.


**1.1. Library**: is a collection of non-volatile resources used by computer programs, often to manage data or perform complex calculations.
One useful example could be the library **math** that improve the readability of formula, moreover, it has preconfigured constants like: π and e. It is part of Python standard library, to exploit its features you must only move from disk to RAM by means `import`.

In [1]:
# To use a library you have to "import" it from Disk memory to RAM
import math

# Let's calculate precisely a Area of a circle with R=1:
R = 1
Area = math.pi * R**2
print(f"The Area of the circle is: {Area}")

# Let's evaluate the square root of 16:
print(f"The square root of 16 is: {math.sqrt(16)}")

The Area of the circle is: 3.141592653589793
The square root of 16 is: 4.0

In [2]:
# To save memory is also possible to import in the RAM only a module:
from math import sqrt

print(sqrt(25))         # 5.0
# print(pi)             # This would fail because we ONLY took sqrt!

5.0

In [3]:
# Moreover, to save time you can use the short name:
import math as m

print(m.factorial(5))   # 120 (5*4*3*2*1)

120

**1.2. pip - Python Package Manager**
pip is a standalone program that serves as a package manager to install python libraries. Practically speaking, if import moves the library from disk to RAM, `pip install` moves it from internet to the disk. Here below will find summarized some useful Python libraries that need to be installed:

In [4]:
# STEP 1: INSTALLATION (Bringing the tool home)
# Run this only once in your notebook
!pip install emoji

# STEP 2: IMPORTING (Putting the tool on the workbench)
import emoji

# STEP 3: USAGE
print(emoji.emojize("Python is fun! :snake: :rocket:"))

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 21.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Python is fun! 🐍 🚀

In [5]:
# Faker: It can generate names, addresses, emails, and even fake profiles in seconds
!pip install Faker
from faker import Faker

fake = Faker()

# Create 5 fake customer profiles
for _ in range(5):
    print(f"Name: {fake.name()} | Job: {fake.job()}")

Collecting Faker
  Downloading faker-40.15.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.15.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 39.9 MB/s eta 0:00:00
Installing collected packages: Faker
Successfully installed Faker-40.15.0
Name: Thomas Burns | Job: Psychotherapist
Name: Alicia Chase | Job: Ecologist
Name: Zachary Lang | Job: Management consultant
Name: Sandy Morris | Job: Youth worker
Name: Victoria Mercado | Job: Health and safety inspector

In [6]:
# tqdm: Have you ever run a loop that takes 30 seconds and wondered if Colab crashed? tqdm (derived from the Arabic word taqadum, meaning "progress") adds a visual progress bar to your loops.
!pip install tqdm
from tqdm import tqdm
import time

# Simulate a long audit of 100 items
for item in tqdm(range(100)):
    time.sleep(0.05) # Simulate "work" happening

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

100%|██████████| 100/100 [00:05<00:00, 19.56it/s]

In [7]:
# Rich: to enrich your plotting
!pip install rich
from rich import print
from rich.table import Table

table = Table(title="Grocery Store Audit")

table.add_column("Item", style="cyan")
table.add_column("Price", style="green")

table.add_row("Apple", "$1.50")
table.add_row("Bread", "$2.20")

print(table)

Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich) (0.1.2)

  Grocery Store
      Audit
┏━━━━━━━┳━━━━━━━┓
┃ Item  ┃ Price ┃
┡━━━━━━━╇━━━━━━━┩
│ Apple │ $1.50 │
│ Bread │ $2.20 │
└───────┴───────┘

## 2. **Functions**
A function is a black-box part of the code used to improve **readability** of the main/backbone code.
When Python hits a function call, it doesn't just read the next line. It performs a Control Flow Jump: it "pauses" the main script, it "jumps" to the function block, it creates a Local Scope (a temporary memory space), runs the code and eventually, goes back to the exact spot left carrying the return value like a courier.
Depending on the complexity of the code, you can define the function before in the same source file and directly use it, or you can define it in a different source file and **import** it.

**2.1. Syntax**
``` python
def myFunction(list_of_input):      # Order matters
---> """
     Block note usually exploited to explain the features of the
     function:
     - input:....
     - output:... Force [kN]..
     """
     myVariable = 1   # Valid only inside the function

     # Do something...
     return list_of_output
```

In [8]:
# A function to retrieve the max in between two numbers:

def myMax(a,b):
   if a>b:
     return a
   else:
     return b
a = 50
b = 5
print(myMax(a,b))

50

In [9]:
# If I have to output more than one variables:
def toUpperLower(input_string):
    upper_string = input_string.upper()
    lower_string = input_string.lower()
    return upper_string, lower_string

myString = 'CiaoCIAOciao'
upper, lower = toUpperLower(myString)
print(upper)
print(lower)
uplow = toUpperLower(myString)
print(uplow)  # In this case I will obtain a tuple (Not changeble item)

CIAOCIAOCIAO

ciaociaociao

('CIAOCIAOCIAO', 'ciaociaociao')

In [10]:
# Parameters of a function:
def myGreater(a,b=0):       # b=0 as default value, if nothing is specified
   return a>b
result = myGreater(-1)
print(result)

# It is possible to reassign the value of b:
result = myGreater(-1,-10)
print(result)

False

True

In [11]:
# Named parameters:
def myFunction(a,b,c,d):
    print(a)
    print(b)
    print(c)
    print(d)
    return a+b+c+d

sum = myFunction(d=1,a=2,c=3,b=4)  # The order doesn't matter if you explicitely call the input variables
print(sum)

sum_2 = myFunction(1,2,3,4)        # In this case the value are assigned order-wise
print(sum_2)

d=4
sum_3 = myFunction(a=1, b=2, c=3, d=d)
print(sum_3)

2

4

3

1

10

1

2

3

4

10

1

2

3

4

10

**2.2. Higher-order function**
In the previous examples we gave variables as input to a function and retrieve output variables. If the input and output of a functions are functions themselves, this is called **higher-order** computing. In the following, it is presented `map` and its syntax. This command will apply a function to all the elements of a list.

In [12]:
# map(function, iterable,...) indicate the list of input to the functions
def toUpper(input_string):
    return input_string.upper()

myList = ['Halo','CIao']
upperList = map(toUpper,myList)
print(upperList)
print(list(upperList))

<map object at 0x7a2005d7cd60>

['HALO', 'CIAO']

**2.3. Anonymous function**
It is called `lambda`: deep inside Python treats it as a function and it returns a function object. Moreover, it is very useful for simple one-liner function (it avoids to define a function from scratch) and whose result is immediately returned. \
``` python
result = lambda parameters:expression
```

In [13]:
# Convert a unit of measure:

diameter_cm = 20
diameter_inch = lambda x: x/2.54
print(f"The lambda fun. is useful to convert a measure from {diameter_cm} cm to {diameter_inch(diameter_cm)} inches")

The lambda fun. is useful to convert a measure from 20 cm to 7.874015748031496 inches

In [14]:
# Convert a list of measures:

diameter_cm = [20,30,40]
diameter_inch = list(map(lambda x: x/2.54, diameter_cm))   # Need to declare as a list()
print(diameter_inch)

[7.874015748031496, 11.811023622047244, 15.748031496062993]

**EX.1 Write a function that performs safety check for a rebar subjected to tensile forces and output the :**
```python
diameter = 10          # [cm]
safety_coeff = 1.15    # [-]
force = 1000           # [N]
E = 2e5                # [MPa]
```

**EX.2 Do the same for this list of rebars**
```python
diameters_inch = [7.5, 8.2, 11.3]  # [inch]
safety_coeff = 1.15    # [-]
force = 2000           # [N]
E = 2e5                # [MPa]
```

## 3. **Classes and Object-oriented Programming (OOP)**

**Keep in mind:**"An Object is an instance of a Class"
ex. BMW 320 is an object from the class Auto

Almost everything is an object at a lower level. It is not strictly necessary to apply this knowledge but it is warmly recommended to understand it.

```python
class TensileBar:
    # 1. THE CONSTRUCTOR (Identity & State)
    def __init__(self, E, phi):
        self.E = E                  # Attribute: steel Young Modulus in MPa
        self.phi = phi              # Attribute: Cross-section diameter in mm
        self.force = 0              # Initial state: No load applied yet

    # 2. THE METHODS (Behavior)
    def apply_load(self, normal_force):
        """Changes the state of the object."""
        self.force = normal_force
        print(f"Applied {self.force} N to {self.name}")

    def get_area(self):
        """Calculates internal stress based on current state."""
        import math
        area = math.pi * ((self.phi/2)**2)
        return area

     def get_resistance(self,area):
        """Calculates internal stress based on current state."""
        resistance = area * self.E
        return resistance
```

**EX.3 Check with Gemini what is the "Inheritance" of a Class. Create a Class called 'Point2D' taking as input the attributes x and y coordinates of a point in Cartesian plane. Define a Method called 'movePoint' that moves P in the plane by dx and dy. Eventually use inheritance to create the class 'Point3D' that manages a point in 3D, updating as well the function movePoint.**

## 4. **Files**
Create, manage and read a .txt file!
- Create a .txt file in your desktop by copy-pasting:
```
    Test_ID: 001 | Status: Pending
    Test_ID: 002 | Status: Pending
    Test_ID: 003 | Status: Pending
```
- drag in the Colab (folder icon on the left-handed side)
- Alternatively, run the code below

In [15]:
# STEP 1: Creating the file
rows = [
    "Test_ID: 001 | Status: Pending \n",
    "Test_ID: 002 | Status: Pending \n",
    "Test_ID: 003 | Status: Pending \n"
]

with open("lab_log.txt", "w") as file:
    file.writelines(rows)

print("File created successfully.")

File created successfully.

In [16]:
# STEP 2: Modifying a specific line
# 1. READ the current state
with open("lab_log.txt", "r") as file:
    data = file.readlines()

# 2. MODIFY the second item (index 1) in our list
# We replace the whole string for that row
data[1] = data[1].replace("Pending", "PASSED")

# 3. WRITE it back (Overwrite mode 'w')
with open("lab_log.txt", "w") as file:
    file.writelines(data)

print("Modification complete: Row 2 updated.")

Modification complete: Row 2 updated.

In [17]:
# STEP 3: Adding a fourth row
new_entry = "Test_ID: 004 | Status: Pending \n"

with open("lab_log.txt", "a") as file:
    file.write(new_entry)

print("New row appended.")

New row appended.

**EX.4 Check with Gemini the difference between a .csv and .tsv file.**

## 5. **Hackathon: the grocery warehouse Pt.2** 📦
A little local grocery store hires you as accountant. They provide to you a list of items in the warehouse and you are in charge of retrieving data from the register and assist the owner to restock, calculate tax and other stuff... But now, you will handle a real dataset.
Luckily, you attended the Computational Data Analysis with Python course and you solved all the tasks of the week in 30 Minutes!!

In [18]:
import kagglehub
path = kagglehub.dataset_download("chinmayshanbhag/big-basket-products")

Using Colab cache for faster access to the 'big-basket-products' dataset.

In [19]:
import os
import pandas as pd
# Database management DO NOT TOUCH THIS!
# List the contents of the downloaded dataset directory to find the CSV file
# The 'path' variable is available from the previous step
dataset_files = os.listdir(path)
csv_files = [f for f in dataset_files if f.endswith('.csv')]

if not csv_files:
    print(f"No CSV files found in the directory: {path}")
    csv_file_path = None
elif len(csv_files) == 1:
    csv_file_name = csv_files[0]
    csv_file_path = os.path.join(path, csv_file_name)
    print(f"Found CSV file: {csv_file_path}")
else:
    print(f"Multiple CSV files found: {csv_files}. Attempting to use the first one: {csv_files[0]}")
    csv_file_name = csv_files[0]
    csv_file_path = os.path.join(path, csv_file_name)

if csv_file_path:
    # Load the CSV file into a pandas DataFrame
    df = pd.read_csv(csv_file_path)

    print("\nFirst 5 rows of the DataFrame:")
    display(df.head(20))

    print("\nLast 5 rows of the DataFrame:")
    display(df.tail())
else:
    print("Could not proceed as no CSV file was found.")

Found CSV file: /kaggle/input/big-basket-products/BigBasket.csv

First 5 rows of the DataFrame:

,ProductName,Brand,Price,DiscountPrice,Image_Url,Quantity,Category,SubCategory,Absolute_Url
0,Onion (Loose),Fresho,69.75,52.00,https://www.bigbasket.com/media/uploads/p/l/40...,2 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/40075537/fresho-o...
1,Onion,Fresho,174.35,130.00,https://www.bigbasket.com/media/uploads/p/l/12...,5 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/1201414/fresho-on...
2,Onion (Loose),Fresho,34.87,26.00,https://www.bigbasket.com/media/uploads/p/l/10...,1 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/10000148/fresho-o...
3,Onion,Fresho,69.74,52.00,https://www.bigbasket.com/media/uploads/p/l/12...,2 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/1201413/fresho-on...
4,Onion (Loose),Fresho,174.37,129.00,https://www.bigbasket.com/media/uploads/p/l/10...,5 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/10000150/fresho-o...
5,"Farm Eggs - Table Tray, Medium, Antibiotic Res...",Fresho,110.00,78.00,https://www.bigbasket.com/media/uploads/p/l/40...,12 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/40072320/fresho-f...
6,"Farm Eggs - Table Tray, Medium, Antibiotic Res...",Fresho,210.00,181.00,https://www.bigbasket.com/media/uploads/p/l/15...,30 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/150502/fresho-far...
7,Potato (Loose),Fresho,50.32,38.75,https://www.bigbasket.com/media/uploads/p/l/40...,1 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/40048457/fresho-p...
8,Potato,Fresho,100.65,77.50,https://www.bigbasket.com/media/uploads/p/l/40...,2 kg,Fruits & Vegetables,"Potato, Onion & Tomato",https://www.bigbasket.com/pd/40162469/fresho-p...
9,Eggs - Regular,Fresho,250.00,250.00,https://www.bigbasket.com/media/uploads/p/l/12...,5x6 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/1205938/fresho-eg...
10,"Farm Eggs - Regular, Medium, Antibiotic Residu...",Fresho,50.00,38.00,https://www.bigbasket.com/media/uploads/p/l/28...,6 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/281204/fresho-far...
11,Eggs - Regular,Fresho,100.00,76.00,https://www.bigbasket.com/media/uploads/p/l/12...,2x6 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/1203477/fresho-eg...
12,Eggs - Regular,Fresho,200.00,200.00,https://www.bigbasket.com/media/uploads/p/l/12...,4x6 pcs,"Eggs, Meat & Fish",Farm Eggs,https://www.bigbasket.com/pd/1205933/fresho-eg...
13,Atta/Godihittu - Whole Wheat,Aashirvaad,119.00,118.00,https://www.bigbasket.com/media/uploads/p/l/16...,2 kg,"Foodgrains, Oil & Masala",Atta Whole Wheat,https://www.bigbasket.com/pd/161826/aashirvaad...
14,Atta/Godihittu - Whole Wheat,Aashirvaad,301.00,292.00,https://www.bigbasket.com/media/uploads/p/l/12...,5 kg,"Foodgrains, Oil & Masala",Atta Whole Wheat,https://www.bigbasket.com/pd/126903/aashirvaad...
15,Atta/Godihittu - Whole Wheat,Aashirvaad,65.00,63.00,https://www.bigbasket.com/media/uploads/p/l/30...,1 kg,"Foodgrains, Oil & Masala",Atta Whole Wheat,https://www.bigbasket.com/pd/30006887/aashirva...
16,"Disinfectant Toilet Cleaner Liquid, Original",Harpic,93.00,93.00,https://www.bigbasket.com/media/uploads/p/l/26...,500 ml,Cleaning & Household,Toilet Cleaners,https://www.bigbasket.com/pd/263754/harpic-pow...
17,Disinfectant Toilet Cleaner Liquid - Original,Harpic,186.00,182.28,https://www.bigbasket.com/media/uploads/p/l/12...,500 ml,Cleaning & Household,Toilet Cleaners,https://www.bigbasket.com/pd/1200366/harpic-or...
18,"Disinfectant Toilet Cleaner Liquid, Original",Harpic,195.00,181.00,https://www.bigbasket.com/media/uploads/p/l/29...,1 L,Cleaning & Household,Toilet Cleaners,https://www.bigbasket.com/pd/298290/harpic-pow...
19,Disinfectant Toilet Cleaner Liquid - Original,Harpic,390.00,360.15,https://www.bigbasket.com/media/uploads/p/l/12...,1 L,Cleaning & Household,Toilet Cleaners,https://www.bigbasket.com/pd/1200277/harpic-di...

Last 5 rows of the DataFrame:

,ProductName,Brand,Price,DiscountPrice,Image_Url,Quantity,Category,SubCategory,Absolute_Url
8203,"Foil Alphabet Balloon - Letter V, Party Decor,...",Bvishal,49.0,25.0,https://www.bigbasket.com/media/uploads/p/l/40...,1 pc,Cleaning & Household,"Caps, Balloons & Candles",https://www.bigbasket.com/pd/40237020/bvishal-...
8204,"Decoration Balls - Used For Parties, Unique De...",Bvishal,399.0,249.0,https://www.bigbasket.com/media/uploads/p/l/40...,6 pcs,Cleaning & Household,Decorations,https://www.bigbasket.com/pd/40237682/bvishal-...
8205,Foundation Blending Brush - 230,PAC,465.0,232.5,https://www.bigbasket.com/media/uploads/p/l/40...,1 pc,Beauty & Hygiene,Makeup Accessories,https://www.bigbasket.com/pd/40175488/pac-foun...
8206,One Week Immunity Booster,The Healthy Company,799.0,799.0,https://www.bigbasket.com/media/uploads/p/l/40...,28 g,Beauty & Hygiene,Supplements & Proteins,https://www.bigbasket.com/pd/40200885/the-heal...
8207,"Blush & Glow - Green Apple Apricot Gel Scrub, ...",Lakme,250.0,175.0,https://www.bigbasket.com/media/uploads/p/l/40...,100 g,Beauty & Hygiene,Face Care,https://www.bigbasket.com/pd/40224773/lakme-bl...

In [20]:
required_columns = ['ProductName', 'Price', 'DiscountPrice', 'Category']
df_filtered = df[required_columns].copy()

# Ensure prices are floats
df_filtered['Price'] = df_filtered['Price'].astype(float)

# Split 'Quantity' into 'qty' and 'unit_of_measure'
df_filtered[['qty', 'unit_of_measure']] = df['Quantity'].str.extract(r'(\d+\.?\d*)\s*([a-zA-Z]+)?')

# Convert 'qty' to numeric (float) and fill any NaN with 0
df_filtered['qty'] = pd.to_numeric(df_filtered['qty'], errors='coerce').fillna(0)

# Handle cases where unit might be missing (e.g., if only a number is present)
df_filtered['unit_of_measure'] = df_filtered['unit_of_measure'].fillna('')


display(df_filtered.head())
display(df_filtered.tail())

,ProductName,Price,DiscountPrice,Category,qty,unit_of_measure
0,Onion (Loose),69.75,52.0,Fruits & Vegetables,2.0,kg
1,Onion,174.35,130.0,Fruits & Vegetables,5.0,kg
2,Onion (Loose),34.87,26.0,Fruits & Vegetables,1.0,kg
3,Onion,69.74,52.0,Fruits & Vegetables,2.0,kg
4,Onion (Loose),174.37,129.0,Fruits & Vegetables,5.0,kg

,ProductName,Price,DiscountPrice,Category,qty,unit_of_measure
8203,"Foil Alphabet Balloon - Letter V, Party Decor,...",49.0,25.0,Cleaning & Household,1.0,pc
8204,"Decoration Balls - Used For Parties, Unique De...",399.0,249.0,Cleaning & Household,6.0,pcs
8205,Foundation Blending Brush - 230,465.0,232.5,Beauty & Hygiene,1.0,pc
8206,One Week Immunity Booster,799.0,799.0,Beauty & Hygiene,28.0,g
8207,"Blush & Glow - Green Apple Apricot Gel Scrub, ...",250.0,175.0,Beauty & Hygiene,100.0,g

In [21]:
# Convert the DataFrame to a list of dictionaries
df_as_dict = df_filtered.to_dict(orient='records')

# Display the first 5 entries of the dictionary list to verify
print("First 5 rows of df_filtered as a list of dictionaries:")
for i in range(min(5, len(df_as_dict))):
    print(df_as_dict[i])

First 5 rows of df_filtered as a list of dictionaries:

{
    'ProductName': 'Onion (Loose)',
    'Price': 69.75,
    'DiscountPrice': 52.0,
    'Category': 'Fruits & Vegetables',
    'qty': 2.0,
    'unit_of_measure': 'kg'
}

{
    'ProductName': 'Onion',
    'Price': 174.35,
    'DiscountPrice': 130.0,
    'Category': 'Fruits & Vegetables',
    'qty': 5.0,
    'unit_of_measure': 'kg'
}

{
    'ProductName': 'Onion (Loose)',
    'Price': 34.87,
    'DiscountPrice': 26.0,
    'Category': 'Fruits & Vegetables',
    'qty': 1.0,
    'unit_of_measure': 'kg'
}

{
    'ProductName': 'Onion',
    'Price': 69.74,
    'DiscountPrice': 52.0,
    'Category': 'Fruits & Vegetables',
    'qty': 2.0,
    'unit_of_measure': 'kg'
}

{
    'ProductName': 'Onion (Loose)',
    'Price': 174.37,
    'DiscountPrice': 129.0,
    'Category': 'Fruits & Vegetables',
    'qty': 5.0,
    'unit_of_measure': 'kg'
}

### **Tasks from your Boss:**

1.  **Categorize items by price using a custom function: add a value to each key identifying the products stating if the item belongs to 'Budget' category if the price is lower than 50, 'Standard' if in the range 50 to 100, and 'Luxury' for higher prices.**
2.  **Calculate the percentage discount for each item using a `lambda` function.**
3.  **Create a list of formatted product descriptions using `map` with a lambda function, the format should be: f"{item['ProductName']} ({item['qty']} {item['unit_of_measure']}) - {item['Category']}".**
4. #### **Build a `GroceryInventoryManager` System using Classes - BONUS if you easily complete previous tasks**

This is a challenging task that requires you to apply your knowledge of classes, attributes, methods, and potentially error handling to simulate a basic inventory management system for the grocery warehouse. You'll encapsulate product data and create an object to manage the entire inventory.

**Part 1: The `Product` Class**

Create a Python class named `Product` to represent individual items in the grocery store. Each `Product` object should have the following attributes and methods:

*   **Attributes:**
    *   `product_name` (string)
    *   `category` (string)
    *   `price` (float, original price)
    *   `discount_price` (float, discounted price)
    *   `quantity` (float, current stock level)
    *   `unit_of_measure` (string, e.g., 'kg', 'unit')
*   **Methods:**
    *   `get_current_selling_price(self)`: Returns the `discount_price` if it's less than the `price` and greater than 0; otherwise, returns the `price`. If `discount_price` is 0, it means no discount is applied.
    *   `calculate_discount_percentage(self)`: Calculates and returns the percentage discount based on `price` and `discount_price`. Return 0 if there's no discount or if `price` is 0 to avoid division by zero. Format as a string (e.g., "25.45%").
    *   `update_stock(self, change)`: Adds `change` to the current `quantity`. If `change` is negative, it simulates a sale. Ensure the `quantity` does not drop below zero. Return `True` if successful, `False` otherwise.
    *   `display_info(self)`: Prints a well-formatted string containing all the product's attributes, its current selling price, and its discount percentage.
    
**Part 2: The `GroceryInventoryManager` Class**

Create a Python class named `GroceryInventoryManager` that will manage a collection of `Product` objects.

*   **Attributes:**
    *   `inventory` (list, to store `Product` objects)

*   **Constructor (`__init__`):** Initialize `inventory` as an empty list.

*   **Methods:**
    *   `add_product(self, product_obj)`: Adds a `Product` object to the `inventory` list. Before adding, check if a product with the same `product_name` already exists. If it does, update its quantity (add to existing stock) instead of adding a duplicate.
    *   `remove_product(self, product_name)`: Removes a `Product` object from the `inventory` by its `product_name`. Handle cases where the product is not found.
    *   `find_product(self, product_name)`: Searches the `inventory` for a product by its `product_name` and returns the `Product` object if found, otherwise returns `None`.
    *   `get_total_inventory_value(self)`: Calculates the sum of (current selling price * quantity) for all products in the inventory. Returns the total value as a float.
    *   `list_products_by_category(self, category)`: Returns a list of `Product` objects that belong to the specified `category`.
    *   `display_all_products(self)`: Iterates through the `inventory` and calls `display_info()` for each `Product` object.

**Part 3: Implementation and Demonstration**

1.  **Initialize Manager:** Create an instance of `GroceryInventoryManager`.
2.  **Populate Inventory:** Use the `df_as_dict` data (from previous Hackathon tasks) to create `Product` objects and add them to your `GroceryInventoryManager` using the `add_product` method. Make sure to handle the `qty` and `unit_of_measure` from `df_as_dict` to initialize the `quantity` and `unit_of_measure` attributes of your `Product` objects.
3.  **Demonstrate Functionality:**
    *   Display the first ten products in the inventory.
    *   Find and display information about a specific product (e.g., 'Onion (Loose)').
    *   Simulate a sale: "sell" 1.5 kg of 'Onion (Loose)' and then display its updated info.
    *   Simulate a restock: "add" 10.0 kg of 'Onion (Loose)' and display its updated info.
    *   Attempt to sell a product in a quantity which is greater than the available one and observe the behaviour.
    *   Calculate and print the `get_total_inventory_value()` of the entire inventory.

Task 1

In [22]:
def categorize_price(df_as_dict):
    for item in df_as_dict:
        price = item["Price"]

        if price < 50:
            item["Category"] = "Budget"
        elif price < 100:
            item["Category"] = "Standard"
        else:
            item["Category"] = "Luxury"

    return df_as_dict

categorize_price(df_as_dict)

[{'ProductName': 'Onion (Loose)',
  'Price': 69.75,
  'DiscountPrice': 52.0,
  'Category': 'Standard',
  'qty': 2.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Onion',
  'Price': 174.35,
  'DiscountPrice': 130.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Onion (Loose)',
  'Price': 34.87,
  'DiscountPrice': 26.0,
  'Category': 'Budget',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Onion',
  'Price': 69.74,
  'DiscountPrice': 52.0,
  'Category': 'Standard',
  'qty': 2.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Onion (Loose)',
  'Price': 174.37,
  'DiscountPrice': 129.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free',
  'Price': 110.0,
  'DiscountPrice': 78.0,
  'Category': 'Luxury',
  'qty': 12.0,
  'unit_of_measure': 'pcs'},
 {'ProductName': 'Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free',
  'Price': 210.0,
  'DiscountPrice': 181.0,
  'Category': 'Luxury',
  'qty': 30.0,
  'unit_of_measure': 'pcs'},
 {'ProductName': 'Potato (Loose)',
  'Price': 50.32,
  'DiscountPrice': 38.75,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Potato',
  'Price': 100.65,
  'DiscountPrice': 77.5,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Eggs - Regular',
  'Price': 250.0,
  'DiscountPrice': 250.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Farm Eggs - Regular, Medium, Antibiotic Residue-Free',
  'Price': 50.0,
  'DiscountPrice': 38.0,
  'Category': 'Standard',
  'qty': 6.0,
  'unit_of_measure': 'pcs'},
 {'ProductName': 'Eggs - Regular',
  'Price': 100.0,
  'DiscountPrice': 76.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Eggs - Regular',
  'Price': 200.0,
  'DiscountPrice': 200.0,
  'Category': 'Luxury',
  'qty': 4.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Atta/Godihittu - Whole Wheat',
  'Price': 119.0,
  'DiscountPrice': 118.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Atta/Godihittu - Whole Wheat',
  'Price': 301.0,
  'DiscountPrice': 292.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Atta/Godihittu - Whole Wheat',
  'Price': 65.0,
  'DiscountPrice': 63.0,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid, Original',
  'Price': 93.0,
  'DiscountPrice': 93.0,
  'Category': 'Standard',
  'qty': 500.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid - Original',
  'Price': 186.0,
  'DiscountPrice': 182.28,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid, Original',
  'Price': 195.0,
  'DiscountPrice': 181.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid - Original',
  'Price': 390.0,
  'DiscountPrice': 360.15,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid - Original',
  'Price': 585.0,
  'DiscountPrice': 543.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid, Original',
  'Price': 40.0,
  'DiscountPrice': 40.0,
  'Category': 'Budget',
  'qty': 200.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Disinfectant Toilet Cleaner Liquid, Original',
  'Price': 390.0,
  'DiscountPrice': 390.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Tomato - Hybrid (Loose)',
  'Price': 26.9,
  'DiscountPrice': 17.5,
  'Category': 'Budget',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Tomato - Hybrid (Loose)',
  'Price': 13.45,
  'DiscountPrice': 9.0,
  'Category': 'Budget',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 40.0,
  'DiscountPrice': 40.0,
  'Category': 'Budget',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 285.0,
  'DiscountPrice': 285.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 145.0,
  'DiscountPrice': 132.0,
  'Category': 'Luxury',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 570.0,
  'DiscountPrice': 526.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'Kg'},
 {'ProductName': 'Paneer - Premium Fresh',
  'Price': 470.0,
  'DiscountPrice': 440.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Paneer - Premium Fresh',
  'Price': 224.0,
  'DiscountPrice': 224.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Paneer - Premium Fresh',
  'Price': 275.0,
  'DiscountPrice': 255.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Paneer - Premium Fresh',
  'Price': 112.0,
  'DiscountPrice': 112.0,
  'Category': 'Luxury',
  'qty': 200.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tomato - Local (Loose)',
  'Price': 25.97,
  'DiscountPrice': 17.5,
  'Category': 'Budget',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Tomato - Local (Loose)',
  'Price': 12.99,
  'DiscountPrice': 9.0,
  'Category': 'Budget',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Carrot - Orange (Loose)',
  'Price': 50.65,
  'DiscountPrice': 39.0,
  'Category': 'Standard',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Carrot - Orange (Loose)',
  'Price': 101.3,
  'DiscountPrice': 78.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Carrot - Orange (Loose)',
  'Price': 25.32,
  'DiscountPrice': 19.5,
  'Category': 'Budget',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': '2-Minute Instant Noodles - Masala',
  'Price': 82.0,
  'DiscountPrice': 72.0,
  'Category': 'Standard',
  'qty': 420.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Masala Instant Noodles Vegetarian',
  'Price': 14.0,
  'DiscountPrice': 14.0,
  'Category': 'Budget',
  'qty': 70.0,
  'unit_of_measure': 'g'},
 {'ProductName': '2-Minute Noodles Masala - Made With Quality Spices, Rich In Fibre',
  'Price': 168.0,
  'DiscountPrice': 156.0,
  'Category': 'Luxury',
  'qty': 70.0,
  'unit_of_measure': 'g'},
 {'ProductName': '2-Minute Instant Masala Noodles - Made With Quality Spices, Source Of Iron',
  'Price': 55.0,
  'DiscountPrice': 52.5,
  'Category': 'Standard',
  'qty': 280.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Masala 2 Minute Instant Noodles',
  'Price': 28.0,
  'DiscountPrice': 28.0,
  'Category': 'Budget',
  'qty': 140.0,
  'unit_of_measure': 'g'},
 {'ProductName': '2-Minute Instant Masala Noodles - Made With Quality Spices, Goodness Of Iron',
  'Price': 109.0,
  'DiscountPrice': 109.0,
  'Category': 'Luxury',
  'qty': 560.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Idly Dosa Batter',
  'Price': 158.0,
  'DiscountPrice': 145.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Idly & Dosa Batter',
  'Price': 79.0,
  'DiscountPrice': 72.5,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'Kg'},
 {'ProductName': 'Bathing Bar Soap - Germ Protection, Original',
  'Price': 600.0,
  'DiscountPrice': 456.0,
  'Category': 'Luxury',
  'qty': 8.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Bathing Bar Soap - Original',
  'Price': 240.0,
  'DiscountPrice': 225.6,
  'Category': 'Luxury',
  'qty': 6.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Original Bathing Bar Soap, Daily Protection from Germs',
  'Price': 75.0,
  'DiscountPrice': 75.0,
  'Category': 'Standard',
  'qty': 125.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Bathing Soap - Original',
  'Price': 300.0,
  'DiscountPrice': 249.0,
  'Category': 'Luxury',
  'qty': 4.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Bathing Soap - Original',
  'Price': 150.0,
  'DiscountPrice': 132.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Bathing Bar Soap - Germ Protection, Original',
  'Price': 450.0,
  'DiscountPrice': 360.0,
  'Category': 'Luxury',
  'qty': 6.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Colgate Strong Teeth, 150 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath',
  'Price': 85.0,
  'DiscountPrice': 85.0,
  'Category': 'Standard',
  'qty': 150.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Colgate Strong Teeth, 500 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath',
  'Price': 244.0,
  'DiscountPrice': 219.6,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Toothpaste - Strong Teeth, Dental Cream, Anti Cavity',
  'Price': 346.0,
  'DiscountPrice': 325.36,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Colgate Strong Teeth, 100 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath',
  'Price': 63.0,
  'DiscountPrice': 63.0,
  'Category': 'Standard',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Colgate Strong Teeth, 300 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath',
  'Price': 173.0,
  'DiscountPrice': 166.0,
  'Category': 'Luxury',
  'qty': 3.0,
  'unit_of_measure': 'pcs'},
 {'ProductName': 'Strong Teeth Anticavity Toothpaste With Amino Shakti - Saver Pack',
  'Price': 488.0,
  'DiscountPrice': 429.45,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Rice/Akki - Raw, Sona Masoori',
  'Price': 70.0,
  'DiscountPrice': 57.0,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Rice/Akki - Raw, Sona Masoori, 12-17 Months Old',
  'Price': 700.0,
  'DiscountPrice': 545.0,
  'Category': 'Luxury',
  'qty': 10.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Sona Masoori Raw Rice/Akki',
  'Price': 1750.0,
  'DiscountPrice': 1245.0,
  'Category': 'Luxury',
  'qty': 25.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Rice/Akki - Raw, Sona Masoori',
  'Price': 350.0,
  'DiscountPrice': 280.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 50.0,
  'DiscountPrice': 39.0,
  'Category': 'Standard',
  'qty': 200.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 200.0,
  'DiscountPrice': 151.0,
  'Category': 'Luxury',
  'qty': 4.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 300.0,
  'DiscountPrice': 219.0,
  'Category': 'Luxury',
  'qty': 6.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 400.0,
  'DiscountPrice': 288.0,
  'Category': 'Luxury',
  'qty': 8.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 600.0,
  'DiscountPrice': 417.6,
  'Category': 'Luxury',
  'qty': 12.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Tender Coconut Water - No Added Sugar, Flavours',
  'Price': 1200.0,
  'DiscountPrice': 806.4,
  'Category': 'Luxury',
  'qty': 24.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Original Extra Virgin Olive Oil',
  'Price': 1400.0,
  'DiscountPrice': 728.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Extra Virgin Olive Oil',
  'Price': 6000.0,
  'DiscountPrice': 3060.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Original Extra Virgin Olive Oil',
  'Price': 2700.0,
  'DiscountPrice': 1377.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Frozen Green Peas',
  'Price': 135.0,
  'DiscountPrice': 99.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Frozen Green Peas',
  'Price': 480.0,
  'DiscountPrice': 378.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Frozen Green Peas',
  'Price': 240.0,
  'DiscountPrice': 189.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'Kg'},
 {'ProductName': 'Frozen Green Peas',
  'Price': 270.0,
  'DiscountPrice': 198.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Tea - Natural Care',
  'Price': 650.0,
  'DiscountPrice': 567.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Tea - Natural Care',
  'Price': 170.0,
  'DiscountPrice': 151.0,
  'Category': 'Luxury',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea - Natural Care',
  'Price': 330.0,
  'DiscountPrice': 296.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea - Natural Care',
  'Price': 65.0,
  'DiscountPrice': 65.0,
  'Category': 'Standard',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Carbon Zinc Battery Red HD AA 1015',
  'Price': 360.0,
  'DiscountPrice': 261.9,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Carbon Zinc Battery Red HD AA 1015',
  'Price': 180.0,
  'DiscountPrice': 135.0,
  'Category': 'Luxury',
  'qty': 10.0,
  'unit_of_measure': 'pcs'},
 {'ProductName': 'Tea',
  'Price': 800.0,
  'DiscountPrice': 730.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'Kg'},
 {'ProductName': 'Tea',
  'Price': 410.0,
  'DiscountPrice': 391.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Rich & Flavourful Tea',
  'Price': 90.0,
  'DiscountPrice': 90.0,
  'Category': 'Standard',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 220.0,
  'DiscountPrice': 220.0,
  'Category': 'Luxury',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Ladies Finger (Loose)',
  'Price': 31.82,
  'DiscountPrice': 24.5,
  'Category': 'Budget',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Ladies Finger (Loose)',
  'Price': 63.64,
  'DiscountPrice': 49.0,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Ladies Finger (Loose)',
  'Price': 15.91,
  'DiscountPrice': 12.25,
  'Category': 'Budget',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables',
  'Price': 105.0,
  'DiscountPrice': 105.0,
  'Category': 'Luxury',
  'qty': 400.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Dry Dog Food - Chicken & Vegetables, For Adult Dogs',
  'Price': 285.0,
  'DiscountPrice': 256.5,
  'Category': 'Luxury',
  'qty': 1.2,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables',
  'Price': 1390.0,
  'DiscountPrice': 1223.2,
  'Category': 'Luxury',
  'qty': 6.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables',
  'Price': 725.0,
  'DiscountPrice': 562.0,
  'Category': 'Luxury',
  'qty': 3.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables',
  'Price': 3160.0,
  'DiscountPrice': 2686.0,
  'Category': 'Luxury',
  'qty': 15.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables',
  'Price': 2220.0,
  'DiscountPrice': 1887.0,
  'Category': 'Luxury',
  'qty': 10.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 66.55,
  'DiscountPrice': 66.55,
  'Category': 'Standard',
  'qty': 125.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 127.77,
  'DiscountPrice': 127.77,
  'Category': 'Luxury',
  'qty': 250.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 214.06,
  'DiscountPrice': 214.06,
  'Category': 'Luxury',
  'qty': 550.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 1641.59,
  'DiscountPrice': 1641.59,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 331.41,
  'DiscountPrice': 331.41,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Antiseptic Disinfectant Liquid',
  'Price': 33.27,
  'DiscountPrice': 33.27,
  'Category': 'Budget',
  'qty': 60.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Cumin/Jeera/Jeerige - Whole',
  'Price': 600.0,
  'DiscountPrice': 380.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Cumin/Jeera/Jeerige - Whole',
  'Price': 300.0,
  'DiscountPrice': 192.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Cumin/Jeera/Jeerige - Whole',
  'Price': 30.0,
  'DiscountPrice': 20.0,
  'Category': 'Budget',
  'qty': 50.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Cumin/Jeera/Jeerige - Whole',
  'Price': 120.0,
  'DiscountPrice': 78.0,
  'Category': 'Luxury',
  'qty': 200.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Cumin/Jeera/Jeerige - Whole',
  'Price': 60.0,
  'DiscountPrice': 40.0,
  'Category': 'Standard',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'GoodLife UHT Treated Toned Milk',
  'Price': 28.0,
  'DiscountPrice': 28.0,
  'Category': 'Budget',
  'qty': 500.0,
  'unit_of_measure': 'ml'},
 {'ProductName': 'Adult Gravy DogÂ\xa0Food - Chicken & Liver Chunks In Gravy, 25 RsÂ\xa0Off Value Pack',
  'Price': 600.0,
  'DiscountPrice': 494.0,
  'Category': 'Luxury',
  'qty': 70.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'GoodLife UHT Treated Toned Milk',
  'Price': 60.0,
  'DiscountPrice': 60.0,
  'Category': 'Standard',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Assam Teas With Gently Rolled Aromatic Long Leaves, Rich & Aromatic Chai, Black Tea',
  'Price': 620.0,
  'DiscountPrice': 527.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'kg'},
 {'ProductName': 'Tea',
  'Price': 145.0,
  'DiscountPrice': 145.0,
  'Category': 'Luxury',
  'qty': 250.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Assam Teas With Gently Rolled Aromatic Long Leaves, Rich & Aromatic Chai, Black Tea',
  'Price': 285.0,
  'DiscountPrice': 232.0,
  'Category': 'Luxury',
  'qty': 500.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 40.0,
  'DiscountPrice': 40.0,
  'Category': 'Budget',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Tea',
  'Price': 885.0,
  'DiscountPrice': 708.0,
  'Category': 'Luxury',
  'qty': 1.5,
  'unit_of_measure': 'Kg'},
 {'ProductName': 'Sun Lite - Sunflower Refined Oil',
  'Price': 189.0,
  'DiscountPrice': 181.0,
  'Category': 'Luxury',
  'qty': 1.0,
  'unit_of_measure': 'L'},
 {'ProductName': 'Sunflower Refined Oil - Sun Lite',
  'Price': 567.0,
  'DiscountPrice': 534.0,
  'Category': 'Luxury',
  'qty': 3.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Cream Beauty Bathing Bar',
  'Price': 128.0,
  'DiscountPrice': 128.0,
  'Category': 'Luxury',
  'qty': 2.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Cream Beauty Bathing Bar',
  'Price': 840.0,
  'DiscountPrice': 651.64,
  'Category': 'Luxury',
  'qty': 3.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Cream Beauty Bathing Bar, Has 1/4th Moisturizing Cream',
  'Price': 64.0,
  'DiscountPrice': 64.0,
  'Category': 'Standard',
  'qty': 100.0,
  'unit_of_measure': 'g'},
 {'ProductName': 'Cream Beauty Bathing Bar',
  'Price': 944.0,
  'DiscountPrice': 802.0,
  'Category': 'Luxury',
  'qty': 5.0,
  'unit_of_measure': 'x'},
 {'ProductName': 'Cream Beauty Bathing Bar - For Soft,\xa0Smooth Skin',
  'Price': 870.0,
  'DiscountPrice': 696.0,
  'Category': 'Luxury',
  'qty': 100.0,
  'unit_of_measure': 'g'},

Task 2

In [23]:
percentage_discount = lambda x: ((x["Price"] - x["DiscountPrice"]) / x["Price"]) * 100

percentage_discount(df_as_dict[1])

25.437338686550042

Task 3

In [24]:
def format_product_info(product):
    return f"{product['ProductName']} ({product['qty']} {product['unit_of_measure']}) - {product['Category']}"

formated_list = map(format_product_info, df_as_dict)
list(formated_list)

['Onion (Loose) (2.0 kg) - Standard',
 'Onion (5.0 kg) - Luxury',
 'Onion (Loose) (1.0 kg) - Budget',
 'Onion (2.0 kg) - Standard',
 'Onion (Loose) (5.0 kg) - Luxury',
 'Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free (12.0 pcs) - Luxury',
 'Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free (30.0 pcs) - Luxury',
 'Potato (Loose) (1.0 kg) - Standard',
 'Potato (2.0 kg) - Luxury',
 'Eggs - Regular (5.0 x) - Luxury',
 'Farm Eggs - Regular, Medium, Antibiotic Residue-Free (6.0 pcs) - Standard',
 'Eggs - Regular (2.0 x) - Luxury',
 'Eggs - Regular (4.0 x) - Luxury',
 'Atta/Godihittu - Whole Wheat (2.0 kg) - Luxury',
 'Atta/Godihittu - Whole Wheat (5.0 kg) - Luxury',
 'Atta/Godihittu - Whole Wheat (1.0 kg) - Standard',
 'Disinfectant Toilet Cleaner Liquid, Original (500.0 ml) - Standard',
 'Disinfectant Toilet Cleaner Liquid - Original (500.0 ml) - Luxury',
 'Disinfectant Toilet Cleaner Liquid, Original (1.0 L) - Luxury',
 'Disinfectant Toilet Cleaner Liquid - Original (1.0 L) - Luxury',
 'Disinfectant Toilet Cleaner Liquid - Original (1.0 L) - Luxury',
 'Disinfectant Toilet Cleaner Liquid, Original (200.0 ml) - Budget',
 'Disinfectant Toilet Cleaner Liquid, Original (1.0 L) - Luxury',
 'Tomato - Hybrid (Loose) (1.0 kg) - Budget',
 'Tomato - Hybrid (Loose) (500.0 g) - Budget',
 'Tea (100.0 g) - Budget',
 'Tea (500.0 g) - Luxury',
 'Tea (250.0 g) - Luxury',
 'Tea (1.0 Kg) - Luxury',
 'Paneer - Premium Fresh (1.0 kg) - Luxury',
 'Paneer - Premium Fresh (2.0 x) - Luxury',
 'Paneer - Premium Fresh (500.0 g) - Luxury',
 'Paneer - Premium Fresh (200.0 g) - Luxury',
 'Tomato - Local (Loose) (1.0 kg) - Budget',
 'Tomato - Local (Loose) (500.0 g) - Budget',
 'Carrot - Orange (Loose) (500.0 g) - Standard',
 'Carrot - Orange (Loose) (1.0 kg) - Luxury',
 'Carrot - Orange (Loose) (250.0 g) - Budget',
 '2-Minute Instant Noodles - Masala (420.0 g) - Standard',
 'Masala Instant Noodles Vegetarian (70.0 g) - Budget',
 '2-Minute Noodles Masala - Made With Quality Spices, Rich In Fibre (70.0 g) - Luxury',
 '2-Minute Instant Masala Noodles - Made With Quality Spices, Source Of Iron (280.0 g) - Standard',
 'Masala 2 Minute Instant Noodles (140.0 g) - Budget',
 '2-Minute Instant Masala Noodles - Made With Quality Spices, Goodness Of Iron (560.0 g) - Luxury',
 'Idly Dosa Batter (2.0 x) - Luxury',
 'Idly & Dosa Batter (1.0 Kg) - Standard',
 'Bathing Bar Soap - Germ Protection, Original (8.0 x) - Luxury',
 'Bathing Bar Soap - Original (6.0 x) - Luxury',
 'Original Bathing Bar Soap, Daily Protection from Germs (125.0 g) - Standard',
 'Bathing Soap - Original (4.0 x) - Luxury',
 'Bathing Soap - Original (2.0 x) - Luxury',
 'Bathing Bar Soap - Germ Protection, Original (6.0 x) - Luxury',
 'Colgate Strong Teeth, 150 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath (150.0 g) - Standard',
 'Colgate Strong Teeth, 500 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath (500.0 g) - Luxury',
 'Toothpaste - Strong Teeth, Dental Cream, Anti Cavity (2.0 x) - Luxury',
 'Colgate Strong Teeth, 100 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath (100.0 g) - Standard',
 'Colgate Strong Teeth, 300 gm, India’s No: 1 Toothpaste Brand, Calcium-boost for 2X Stronger Teeth, Prevents cavities, Whitens Teeth,\xa0 Freshens Breath (3.0 pcs) - Luxury',
 'Strong Teeth Anticavity Toothpaste With Amino Shakti - Saver Pack (2.0 x) - Luxury',
 'Rice/Akki - Raw, Sona Masoori (1.0 kg) - Standard',
 'Rice/Akki - Raw, Sona Masoori, 12-17 Months Old (10.0 kg) - Luxury',
 'Sona Masoori Raw Rice/Akki (25.0 kg) - Luxury',
 'Rice/Akki - Raw, Sona Masoori (5.0 kg) - Luxury',
 'Tender Coconut Water - No Added Sugar, Flavours (200.0 ml) - Standard',
 'Tender Coconut Water - No Added Sugar, Flavours (4.0 x) - Luxury',
 'Tender Coconut Water - No Added Sugar, Flavours (6.0 x) - Luxury',
 'Tender Coconut Water - No Added Sugar, Flavours (8.0 x) - Luxury',
 'Tender Coconut Water - No Added Sugar, Flavours (12.0 x) - Luxury',
 'Tender Coconut Water - No Added Sugar, Flavours (24.0 x) - Luxury',
 'Original Extra Virgin Olive Oil (1.0 L) - Luxury',
 'Extra Virgin Olive Oil (5.0 L) - Luxury',
 'Original Extra Virgin Olive Oil (2.0 L) - Luxury',
 'Frozen Green Peas (500.0 g) - Luxury',
 'Frozen Green Peas (2.0 x) - Luxury',
 'Frozen Green Peas (1.0 Kg) - Luxury',
 'Frozen Green Peas (2.0 x) - Luxury',
 'Tea - Natural Care (1.0 kg) - Luxury',
 'Tea - Natural Care (250.0 g) - Luxury',
 'Tea - Natural Care (500.0 g) - Luxury',
 'Tea - Natural Care (100.0 g) - Standard',
 'Carbon Zinc Battery Red HD AA 1015 (2.0 x) - Luxury',
 'Carbon Zinc Battery Red HD AA 1015 (10.0 pcs) - Luxury',
 'Tea (1.0 Kg) - Luxury',
 'Tea (500.0 g) - Luxury',
 'Rich & Flavourful Tea (100.0 g) - Standard',
 'Tea (250.0 g) - Luxury',
 'Ladies Finger (Loose) (500.0 g) - Budget',
 'Ladies Finger (Loose) (1.0 kg) - Standard',
 'Ladies Finger (Loose) (250.0 g) - Budget',
 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables (400.0 g) - Luxury',
 'Dry Dog Food - Chicken & Vegetables, For Adult Dogs (1.2 kg) - Luxury',
 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables (6.0 kg) - Luxury',
 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables (3.0 kg) - Luxury',
 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables (15.0 kg) - Luxury',
 'Dry Pet Food - For Adult Dogs, Chicken & Vegetables (10.0 kg) - Luxury',
 'Antiseptic Disinfectant Liquid (125.0 ml) - Standard',
 'Antiseptic Disinfectant Liquid (250.0 ml) - Luxury',
 'Antiseptic Disinfectant Liquid (550.0 ml) - Luxury',
 'Antiseptic Disinfectant Liquid (5.0 L) - Luxury',
 'Antiseptic Disinfectant Liquid (1.0 L) - Luxury',
 'Antiseptic Disinfectant Liquid (60.0 ml) - Budget',
 'Cumin/Jeera/Jeerige - Whole (1.0 kg) - Luxury',
 'Cumin/Jeera/Jeerige - Whole (500.0 g) - Luxury',
 'Cumin/Jeera/Jeerige - Whole (50.0 g) - Budget',
 'Cumin/Jeera/Jeerige - Whole (200.0 g) - Luxury',
 'Cumin/Jeera/Jeerige - Whole (100.0 g) - Standard',
 'GoodLife UHT Treated Toned Milk (500.0 ml) - Budget',
 'Adult Gravy DogÂ\xa0Food - Chicken & Liver Chunks In Gravy, 25 RsÂ\xa0Off Value Pack (70.0 g) - Luxury',
 'GoodLife UHT Treated Toned Milk (1.0 L) - Standard',
 'Assam Teas With Gently Rolled Aromatic Long Leaves, Rich & Aromatic Chai, Black Tea (1.0 kg) - Luxury',
 'Tea (250.0 g) - Luxury',
 'Assam Teas With Gently Rolled Aromatic Long Leaves, Rich & Aromatic Chai, Black Tea (500.0 g) - Luxury',
 'Tea (100.0 g) - Budget',
 'Tea (1.5 Kg) - Luxury',
 'Sun Lite - Sunflower Refined Oil (1.0 L) - Luxury',
 'Sunflower Refined Oil - Sun Lite (3.0 x) - Luxury',
 'Cream Beauty Bathing Bar (2.0 x) - Luxury',
 'Cream Beauty Bathing Bar (3.0 x) - Luxury',
 'Cream Beauty Bathing Bar, Has 1/4th Moisturizing Cream (100.0 g) - Standard',
 'Cream Beauty Bathing Bar (5.0 x) - Luxury',
 'Cream Beauty Bathing Bar - For Soft,\xa0Smooth Skin (100.0 g) - Luxury',
 'Cream Beauty Bathing Bar, Has 1/4th Moisturizing Cream (125.0 g) - Luxury',
 'Cream Beauty Bathing Bar (6.0 x) - Luxury',
 'Cream Beauty Bathing Bar, Has 1/4th Moisturizing Cream (125.0 g) - Luxury',
 'Cream Beauty Bathing Bar Soap (8.0 x) - Luxury',
 'Sunrise Instant Coffee - Chicory Mixture (50.0 g) - Standard',
 'Sunrise Rich Aroma (500.0 g) - Luxury',
 'Sunrise Instant Coffee Powder - Chicory Mix, Extra Strong (1.0 kg) - Luxury',
 'Sunrise Instant Coffee - Chicory Mix, Rich In Aroma & Flavour (100.0 g) - Luxury',
 'Sunrise Instant Coffee-Chicory Mix, Rich In Aroma & Flavour, (10.0 g) - Budget',
 'Sunrise Instant Coffee (5.5 g) - Budget',
 'Sunrise Instant Coffee - Chicory Mix, Rich In Aroma & Flavour (200.0 g) - Luxury',
 'Gulabari Premium Rose Water - Paraben Free Skin Toner (2.0 x) - Luxury',
 'Gulabari Premium Rose Water - Daily Glow, All Skin Types, Paraben Free, Alcohol Free (250.0 ml) - Standard',
 'Gulabari Premium Rose Water - Daily Glow, All Skin Types, Paraben Free, Alcohol Free (120.0 ml) - Standard',
 'Pasteurised Butter (500.0 g) - Luxury',
 'Butter - Pasteurized (2.0 x) - Luxury',
 'Butter - Pasteurized (2.0 x) - Luxury',
 'Butter - Pasteurised (3.0 x) - Luxury',
 'Pasteurised Butter (100.0 g) - Standard',
 'Butter - Pasteurized (4.0 x) - Luxury',
 'Farm Fresh Curd/Dahi - Premium, No Preservatives (500.0 g) - Budget',
 'Farm Fresh Curd/Dahi - Premium, No Preservatives (2.0 x) - Standard',
 'Chana Dal/Kadale Bele (1.0 kg) - Luxury',
 'Chana Dal/Kadale Bele (2.0 kg) - Luxury',
 'Chana Dal/Kadale Bele (500.0 g) - Standard',
 'Maida (1.0 kg) - Standard',
 'Maida (2.0 kg) - Luxury',
 'Maida (500.0 g) - Budget',
 'Maida (5.0 x) - Luxury',
 'Moong - Green, Whole/Sabut (500.0 g) - Standard',
 'Green Moong Whole/Hesaru Kaalu - Sabut (1.0 kg) - Luxury',
 'Black Soft Drink - Max Taste, Zero Sugar(Diet) (250.0 ml) - Budget',
 'Poha /Avalakki/Aval/Chivda -Thick (500.0 g) - Budget',
 'Poha/Avalakki/Aval/Chivda Thick - Flattened & Beaten Rice , Makers Breakfast &\xa0 Teatime Snacks (1.0 kg) - Standard',
 'Diaper Pants - XXL (16.0 pcs) - Luxury',
 'All-Round Protection Diaper Pants - XXL, 15-25 kg, Ultra Absorb Core, Leakage Prevention for upto 12 Hours (42.0 pcs) - Luxury',
 'Urad Dal/Uddina Bele - Split (1.0 kg) - Luxury',
 'Urad Dal/Uddina Bele - Split (500.0 g) - Luxury',
 'Mustard/Sasive/Rai - Small (500.0 g) - Luxury',
 'Mustard/Sasive/Rai - Small (100.0 g) - Budget',
 'Mustard/Sasive/Rai - Small (1.0 kg) - Luxury',
 'Mustard/Sasive/Rai - Small (200.0 g) - Standard',
 'Organic - Almond/Badam (500.0 g) - Luxury',
 'Organic - Almond/Badam (1.0 kg) - Luxury',
 'Organic - Almond/Badam (100.0 g) - Luxury',
 'Organic - Almond/Badam (200.0 g) - Luxury',
 'Ridge Gourd (500.0 g) - Budget',
 'Ridge Gourd (1.0 kg) - Standard',
 'H2O Unbreakable Water Bottle - Blue (6.0 x) - Luxury',
 'H2o Unbreakable Water Bottle - Blue (1.0 L) - Luxury',
 'H2O Unbreakable Water Bottle - Blue (3.0 x) - Luxury',
 'H2O Unbreakable Water Bottle - Blue (2.0 x) - Luxury',
 'Coccinia (Loose) (1.0 kg) - Standard',
 'Coccinia (Loose) (250.0 g) - Budget',
 'Coccinia (Loose) (500.0 g) - Budget',
 'Oats Breakfast Cereal - Rich In Protein, Dietary Fibre, Nutritious, Easy To Cook (1.0 Kg) - Luxury',
 'Oats Breakfast Cereal - Rich In Protein, Dietary Fibre, Nutritious, Easy To Cook (400.0 g) - Standard',
 'Oats - Multigrain, Breakfast Cereal, Rich In Fibre & Calcium, Good For Heart (600.0 g) - Luxury',
 'Oats Breakfast Cereal - Rich In Protein, Dietary Fibre, Nutritious, Easy To Cook (1.5 Kg) - Luxury',
 'Rolled Oats - Rich In Protein, Nutritious, Easy To Cook (2.0 Kg) - Luxury',
 'Premium Stainless Steel Kitchen Knife - Large, Multipurpose, BBPK02 (1.0 pc) - Luxury',
 'Sooji - Bansi (500.0 g) - Budget',
 'Bansi Sooji (1.0 kg) - Standard',
 'Palak 250g+Ladies Finger 500g+Cucumber 1kg+Capsicum Green 500g+Bottle Gourd 1pc (0.0 ) - Luxury',
 'Intensive Care Cocoa Glow Body Lotion - With Shea Butter, Non-Greasy Formula (400.0 ml) - Luxury',
 'Radish - White (Loose) (1.0 kg) - Budget',
 'Radish - White (Loose) (500.0 g) - Budget',
 'Organic - Brown Sugar/Sakkare (5.0 kg) - Luxury',
 'Organic - Brown Sugar/Sakkare (500.0 g) - Standard',
 'Organic - Brown Sugar/Sakkare (1.0 kg) - Luxury',
 'Organic - Brown Sugar/Sakkare (2.0 kg) - Luxury',
 'Besan Fine/Kadale Hittu (500.0 g) - Standard',
 'Besan Fine/Kadale Hittu (1.0 kg) - Luxury',
 'Rice - Flour (1.0 kg) - Standard',
 'Rice - Flour (500.0 g) - Budget',
 'Premium Care Diapers - Large (88.0 pcs) - Luxury',
 'Premium Care Diapers - Large (13.0 pcs) - Luxury',
 'Premium Care Diaper Pants - Large, 9-14 kg, Air Channels, Lotion with Aloe Vera (30.0 pcs) - Luxury',
 'Premium Care Diaper Pants - Large, 9-14 kg, Lotion with Aloe Vera (132.0 pcs) - Luxury',
 'Premium Care Diapers - Large (44.0 pcs) - Luxury',
 'Marvel 20 Multi Storage Plastic Basket Without Lid - Matt Brown (4.5 L) - Luxury',
 'Moong Dal/Hesaru Bele (500.0 g) - Luxury',
 'Moong Dal/Hesaru Bele (1.0 kg) - Luxury',
 'Moong Dal/Hesaru Bele (2.0 kg) - Luxury',
 'Soft Drink (250.0 ml) - Budget',
 'Brinjal - Bottle Shape (Loose) (1.0 kg) - Standard',
 'Brinjal - Bottle Shape (Loose) (500.0 g) - Budget',
 'Bathing Soap - Skincare (2.0 x) - Standard',
 'Bathing Bar Soap - Skincare (6.0 x) - Luxury',
 'Germ Protection Bathing Soap Bar (8.0 x) - Luxury',
 'Bathing Bar Soap - Skincare (6.0 x) - Luxury',
 'Bathing Soap - Skincare (2.0 x) - Luxury',
 'Germ Protection Bathing Soap Bar (4.0 x) - Luxury',
 'Skincare Pure Glycerine Soap, Protection from Skin Infection Causing Germs (75.0 g) - Budget',
 'Skincare Pure Glycerine Soap, Protection from Skin Infection Causing Germs (125.0 g) - Standard',
 'Idli Rice (1.0 kg) - Standard',
 'Idli Rice (5.0 kg) - Luxury',
 'Idli Rice (10.0 kg) - Luxury',
 'Idli Rice (2.0 kg) - Luxury',
 'Atta Sharbati 100% Mp Whole Wheat, Rotis Stay Softer For Longer (1.0 kg) - Standard',
 'Atta Sharbati 100% MP Whole Wheat Rotis Stay Softer For Longer (5.0 kg) - Luxury',
 'Superior-Mp-Sharbati-Atta/Godihittu - Fortified (500.0 g) - Budget',
 '100% MP Sharbati Atta (2.0 x) - Luxury',
 'Atta Sharbati 100% Mp Whole Wheat, Rotis Stay Softer For Longer (10.0 kg) - Luxury',
 'Methi/Venthaya Keerai - Cleaned, without roots (250.0 g) - Standard',
 'Methi/Venthaya Keerai - Cleaned, without roots (500.0 g) - Luxury',
 'Methi - With roots (200.0 g) - Standard',
 'Methi/Venthaya Keerai - Cleaned, without roots (100.0 g) - Budget',
 'Methi/Venthaya Keerai - Cleaned, without roots (1.0 kg) - Luxury',
 'Durum Wheat Pasta - Fusilli (500.0 g) - Luxury',
 'BB Royal Organic  Kashmir Honey, 500 g + iD Fresho Idly Dosa Batter, 1 Kg (0.0 ) - Luxury',
 'Extra Virgin Olive Oil (1.0 L) - Luxury',
 'Chicken Breast - Boneless, Antibiotic Residue-Free, 4 To 6 pcs (1.0 kg) - Luxury',
 'Chicken Breast - Boneless, Antibiotic Residue-Free, 2- 4 pcs (500.0 g) - Luxury',
 'Chicken Breast - Boneless, Antibiotic Residue-Free, 1 To 2 pcs (250.0 g) - Luxury',
 'Garlic (Loose) (1.0 kg) - Luxury',
 'Garlic (Loose) (250.0 g) - Budget',
 'Urad - Whole/Gota (1.0 kg) - Luxury',
 'Urad - Whole/Gota (500.0 g) - Luxury',
 'Urad Gota - Whole (2.0 kg) - Luxury',
 'Ginger (Loose) (1.0 kg) - Luxury',
 'Ginger (Loose) (100.0 g) - Budget',
 'Ginger (Loose) (250.0 g) - Budget',
 'Ginger (Loose) (500.0 g) - Standard',
 'Premium Natural Californian Almonds (2.0 x) - Luxury',
 'California Almonds (200.0 g) - Luxury',
 'Brinjal Bottle Shape 500 g + Cauliflower 1 pc + Cabbage 1 pc (0.0 ) - Luxury',
 'Gold - Pro Healthy Lifestyle Edible Oil (3.0 X) - Luxury',
 'Gold Refined Cooking oil | Blended Rice Bran & Sunflower oil | Helps Keeps Heart Healthy (1.0 L) - Luxury',
 'Carrot - Ooty (Loose) (1.0 kg) - Luxury',
 'Carrot - Ooty (Loose) (250.0 g) - Standard',
 'Carrot - Ooty (Loose) (500.0 g) - Luxury',
 'Borosilicate Glass Food/Tiffin/Storage Container - With PP Lid, Rectangular, Green (370.0 ml) - Luxury',
 'Borosilicate Glass Food/Tiffin/Storage Container - With PP Lid, Rectangular, Green (640.0 ml) - Luxury',
 'Borosilicate Glass Food/Tiffin/Storage Container - With PP Lid, Rectangular, Blue (370.0 ml) - Luxury',
 'Borosilicate Glass Food/Tiffin/Storage Container - With PP Lid, Rectangular, Green (1.05 L) - Luxury',
 'Mustard/Sasive/Rai - Big (200.0 g) - Standard',
 'Mustard/Sasive/Rai - Big (500.0 g) - Luxury',
 'Mustard/Sasive/Rai - Big (1.0 kg) - Luxury',
 'Mustard/Sasive/Rai - Big (100.0 g) - Budget',
 'Avalakki  Medium - Flattened & Beaten Rice , Makers Breakfast &\xa0 Teatime Snacks (1.0 kg) - Standard',
 'Avalakki Medium - Flattened & Beaten Rice , Makers Breakfast &\xa0 Teatime Snacks (500.0 g) - Budget',
 'Bright Beauty Spot-less Fairness & Germ Removal Face Wash (100.0 g) - Luxury',
 'Bright Beauty Spot-less Fairness & Germ Removal Facewash (3.0 x) - Luxury',
 'Bright Beauty Spot-less Fairness & Germ Removal Facewash (200.0 g) - Luxury',
 'Bright Beauty Spot-less Fairness & Germ Removal Facewash (50.0 g) - Standard',
 'Bright Beauty Spot-less Fairness & Germ Removal Facewash (150.0 g) - Luxury',
 'Sooji - Ordinary, 1 kg + Besan Flour, 1 kg + Maida, 1 kg (0.0 ) - Luxury',
 'Besan Flour, 500 gm + Maida, 500 gm + Sooji - Ordinary, 500 gm (0.0 ) - Luxury',
 'Sooji - Ordinary, 1 kg + Besan Flour, 1 kg + Maida 1 kg (0.0 ) - Luxury',
 'Organic - Sugar (2.0 x) - Luxury',
 'Organic - Sugar/Sakkare (2.0 kg) - Luxury',
 'Organic - Sugar/Sakkare (1.0 kg) - Luxury',
 'Organic - Sugar/Sakkare (5.0 kg) - Luxury',
 'Chicken Curry Cut Without Skin 500 g + Chicken Breast - Boneless 500 g (0.0 ) - Luxury',
 'Chicken Curry Cut Without Skin 500 g + Chicken Breast - Boneless 500 g (0.0 ) - Luxury',
 'Chana - Brown/Kadale Kaalu (1.0 kg) - Luxury',
 'Chana - Brown/Kadale Kaalu (500.0 g) - Standard',
 'Idli - Sooji 2kg + Sugar 2kg + Peanuts/ Mungaphali/Shengdana - Raw 500gm (0.0 ) - Luxury',
 'Premium Care Diapers - Extra Large (108.0 pcs) - Luxury',
 'Premium Care Diaper Pants - XL, 12-17 kg, Lotion with Aloe Vera (72.0 pcs) - Luxury',
 'Premium Care Diaper Pants - Extra Large, 12-17 kg, Lotion with Aloe Vera (11.0 pcs) - Luxury',
 'Premium Care Diaper Pants - Extra Large, 12-17 kg, Lotion with Aloe Vera (24.0 pcs) - Luxury',
 'Premium Care Diaper Pants - XL, 12-17 kg, Lotion with Aloe Vera (36.0 pcs) - Luxury',
 'Organic Jaggery/Bella Powder (500.0 g) - Standard',
 'Organic Jaggery/Bella Powder (1.0 kg) - Luxury',
 'Fresho Palak - Without Root 250 Gm + Amul Malai Paneer 200 Gm (0.0 ) - Luxury',
 'Baby Lips Lip Balm (4.0 g) - Luxury',
 'Premium Natural Whole Cashews (200.0 g) - Luxury',
 'Cashews - Whole, 100% Natural Premium (2.0 x) - Luxury',
 'Red Chilli with Stem 500 gm + Coriander Seeds 500 gm + Cumin - Whole 100 gm (0.0 ) - Luxury',
 'Red Chilli/Lal Mirch 200g + Coriander/Dhania Seeds 200g + Cumin/Jeera Whole 200g (0.0 ) - Luxury',
 'Nacho Chips - Jalapeno (150.0 g) - Standard',
 'Nacho Chips - Jalapeno (2.0 x) - Standard',
 'Nacho Chips - Jalapeno (2.0 x) - Luxury',
 'Nacho Chips - Jalapeno (60.0 g) - Budget',
 'Carbon Zinc Battery Red HD AAA 1012 (2.0 x) - Luxury',
 '1012 Carbon Zinc Battery - AAA (10.0 pcs) - Luxury',
 'Coriander Seeds/Kottambari Beeja (200.0 g) - Luxury',
 'Coriander Seeds/Kottambari Beeja (100.0 g) - Standard',
 'Coriander / Dhania Seeds (50.0 g) - Budget',
 'Coriander Seeds/Kottambari Beeja (500.0 g) - Luxury',
 'Chilli - Green Long, Medium (Loose) (100.0 g) - Budget',
 'Chilli - Green Long, Medium (Loose) (250.0 g) - Budget',
 'Chilli - Green Long, Medium (Loose) (500.0 g) - Standard',
 'Chilli - Green Long, Medium (Loose) (1.0 kg) - Luxury',
 'Body Milk Nourishing Lotion - Very Dry Skin, With Deep Moisture Serum & 2X Almond Oil (120.0 ml) - Standard',
 'Body Lotion - Nourishing Body Milk, For Very Dry Skin (3.0 x) - Luxury',
 'Body Milk Nourishing Lotion - Very Dry Skin, With Deep Moisture Serum & 2X Almond Oil, 48h Intensive Moisture Care (400.0 ml) - Luxury',
 'Chiroti Sooji 1 kg + Ordinary Sooji 1 kg + Bansi Sooji 1 kg (0.0 ) - Luxury',
 'Keratin Smooth Pro Collection Shampoo - Keratin & Argan Oil, Lower Sulphate Formula, Upto 100% Smoother Shiny Hair (180.0 ml) - Luxury',
 'Keratin Smooth Pro Collection Shampoo - Keratin & Argan Oil, Lower Sulphate Formula, Upto 100% Smoother Shiny Hair (80.0 ml) - Standard',
 'Keratin Smooth Pro Collection Shampoo - Keratin & Argan Oil, Lower Sulphate Formula, Upto 100% Smoother Shiny Hair (1.0 L) - Luxury',
 'Keratin Smooth Pro Collection Shampoo - Keratin & Argan Oil, Lower Sulphate Formula, Upto 100% Smoother Shiny Hair (340.0 ml) - Luxury',
 'Keratin Smooth Pro Collection Shampoo - Keratin & Argan Oil, Upto 100% Smoother Shiny Hair (580.0 ml) - Luxury',
 'Organic - Cardamom/Elachi Green (2.0 x) - Luxury',
 'Cardamom Green/Elakki (50.0 g) - Luxury',
 'Organic - Cardamom Green/Elakki (100.0 g) - Luxury',
 'Organic - Cardamom Green/Elakki (20.0 g) - Luxury',
 'Curry Leaves (100.0 g) - Budget',
 'Curry Leaves (250.0 g) - Budget',
 'Curry Leaves (1.0 kg) - Luxury',
 'Bitter Gourd (Loose) (1.0 kg) - Standard',

Task 4

In [31]:
# Part 1


class Product:

  def __init__(self, product_name, category, price, discount_price, quantity, unit_of_measure):
    self.product_name = product_name
    self.category = category
    self.price = price
    self.discount_price = discount_price
    self.quantity = quantity
    self.unit_of_measure = unit_of_measure

  def get_current_selling_price(self):
    if 0 < self.discount_price < self.price:
      return self.discount_price
    return self.price

  def calculate_discount_percentage(self):
    if self.price == 0 or self.discount_price == 0:
        return "0.00%"
    discount = ((self.price - self.discount_price) / self.price) * 100
    return f"{discount:.2f}%"

  def update_stock(self, change):
    if self.quantity + change < 0:
      return False
    self.quantity += change
    return True

  def display_info(self):
      """Prints a formatted summary of the product."""
      selling_price = self.get_current_selling_price()
      discount_pct  = self.calculate_discount_percentage()
      print(
          f"  {'─' * 50}\n"
          f"  Product       : {self.product_name}\n"
          f"  Category      : {self.category}\n"
          f"  Original Price: ${self.price:.2f}\n"
          f"  Discount Price: ${self.discount_price:.2f}\n"
          f"  Selling Price : ${selling_price:.2f}\n"
          f"  Discount      : {discount_pct}\n"
          f"  Stock         : {self.quantity} {self.unit_of_measure}"
      )

In [36]:
# Part 2

class GroceryInventoryManager:

    def __init__(self):
        self.inventory = []

    def add_product(self, product_obj):
      for product in self.inventory:
        if product.product_name == product_obj.product_name:
          product.quantity += product_obj.quantity
          return
      self.inventory.append(product_obj)

    def remove_product(self, product_name):
      for product in self.inventory:
          if product.product_name == product_name:
              self.inventory.remove(product)
              return
      print(f"Product '{product_name}' not found in inventory.")

    def find_product(self, product_name):
        for product in self.inventory:
            if product.product_name == product_name:
                return product
        return None

    def get_total_inventory_value(self):
        total = 0.0
        for product in self.inventory:
            total += product.get_current_selling_price() * product.quantity
        return total

    def list_products_by_category(self, category):
        return [product for product in self.inventory if product.category == category]

    def display_all_products(self):
        for product in self.inventory:
            product.display_info()

In [37]:
# Part 3

# 1. Initialize Manager
manager = GroceryInventoryManager()

# 2. Populate Inventory from df_as_dict
for item in df_as_dict:
    product = Product(
        product_name=item['ProductName'],
        category=item['Category'],
        price=float(item['Price']),
        discount_price=float(item['DiscountPrice']),
        quantity=float(item['qty']),
        unit_of_measure=item['unit_of_measure']
    )
    manager.add_product(product)

print(f"Inventory populated with {len(manager.inventory)} unique products.\n")

# 3a. Display the first 10 products
print("=" * 55)
print("  FIRST 10 PRODUCTS IN INVENTORY")
print("=" * 55)
for product in manager.inventory[:10]:
    product.display_info()

# 3b. Find and display a specific product
print("\n" + "=" * 55)
print("  FIND: 'Onion (Loose)'")
print("=" * 55)
onion = manager.find_product('Onion (Loose)')
if onion:
    onion.display_info()
else:
    print("Product 'Onion (Loose)' not found in inventory.")

# 3c. Simulate a sale: sell 1.5 kg of 'Onion (Loose)'
print("\n" + "=" * 55)
print("  SALE: Selling 1.5 kg of 'Onion (Loose)'")
print("=" * 55)
if onion:
    success = onion.update_stock(-1.5)
    if success:
        print("Sale of 1.5 kg successful!")
    else:
        print("Sale failed: insufficient stock.")
    onion.display_info()

# 3d. Simulate a restock: add 10.0 kg of 'Onion (Loose)'
print("\n" + "=" * 55)
print("  RESTOCK: Adding 10.0 kg of 'Onion (Loose)'")
print("=" * 55)
if onion:
    onion.update_stock(10.0)
    print("Restocked 10.0 kg successfully!")
    onion.display_info()

# 3e. Attempt to sell more than available stock
print("\n" + "=" * 55)
print("  OVERSELL ATTEMPT on 'Onion (Loose)'")
print("=" * 55)
if onion:
    oversell_qty = onion.quantity + 100
    success = onion.update_stock(-oversell_qty)
    if not success:
        print(
            f"Sale FAILED: tried to sell {oversell_qty} {onion.unit_of_measure} "
            f"but only {onion.quantity} {onion.unit_of_measure} in stock."
        )

# 3f. Total inventory value
print("\n" + "=" * 55)
total_value = manager.get_total_inventory_value()
print(f"  TOTAL INVENTORY VALUE: ${total_value:,.2f}")
print("=" * 55)

Inventory populated with 6769 unique products.

=======================================================

  FIRST 10 PRODUCTS IN INVENTORY

=======================================================

  ──────────────────────────────────────────────────
  Product       : Onion (Loose)
  Category      : Standard
  Original Price: $69.75
  Discount Price: $52.00
  Selling Price : $52.00
  Discount      : 25.45%
  Stock         : 8.0 kg

  ──────────────────────────────────────────────────
  Product       : Onion
  Category      : Luxury
  Original Price: $174.35
  Discount Price: $130.00
  Selling Price : $130.00
  Discount      : 25.44%
  Stock         : 7.0 kg

  ──────────────────────────────────────────────────
  Product       : Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free
  Category      : Luxury
  Original Price: $110.00
  Discount Price: $78.00
  Selling Price : $78.00
  Discount      : 29.09%
  Stock         : 42.0 pcs

  ──────────────────────────────────────────────────
  Product       : Potato (Loose)
  Category      : Standard
  Original Price: $50.32
  Discount Price: $38.75
  Selling Price : $38.75
  Discount      : 22.99%
  Stock         : 1.0 kg

  ──────────────────────────────────────────────────
  Product       : Potato
  Category      : Luxury
  Original Price: $100.65
  Discount Price: $77.50
  Selling Price : $77.50
  Discount      : 23.00%
  Stock         : 2.0 kg

  ──────────────────────────────────────────────────
  Product       : Eggs - Regular
  Category      : Luxury
  Original Price: $250.00
  Discount Price: $250.00
  Selling Price : $250.00
  Discount      : 0.00%
  Stock         : 11.0 x

  ──────────────────────────────────────────────────
  Product       : Farm Eggs - Regular, Medium, Antibiotic Residue-Free
  Category      : Standard
  Original Price: $50.00
  Discount Price: $38.00
  Selling Price : $38.00
  Discount      : 24.00%
  Stock         : 6.0 pcs

  ──────────────────────────────────────────────────
  Product       : Atta/Godihittu - Whole Wheat
  Category      : Luxury
  Original Price: $119.00
  Discount Price: $118.00
  Selling Price : $118.00
  Discount      : 0.84%
  Stock         : 8.0 kg

  ──────────────────────────────────────────────────
  Product       : Disinfectant Toilet Cleaner Liquid, Original
  Category      : Standard
  Original Price: $93.00
  Discount Price: $93.00
  Selling Price : $93.00
  Discount      : 0.00%
  Stock         : 702.0 ml

  ──────────────────────────────────────────────────
  Product       : Disinfectant Toilet Cleaner Liquid - Original
  Category      : Luxury
  Original Price: $186.00
  Discount Price: $182.28
  Selling Price : $182.28
  Discount      : 2.00%
  Stock         : 502.0 ml

=======================================================

  FIND: 'Onion (Loose)'

=======================================================

  ──────────────────────────────────────────────────
  Product       : Onion (Loose)
  Category      : Standard
  Original Price: $69.75
  Discount Price: $52.00
  Selling Price : $52.00
  Discount      : 25.45%
  Stock         : 8.0 kg

=======================================================

  SALE: Selling 1.5 kg of 'Onion (Loose)'

=======================================================

Sale of 1.5 kg successful!

  ──────────────────────────────────────────────────
  Product       : Onion (Loose)
  Category      : Standard
  Original Price: $69.75
  Discount Price: $52.00
  Selling Price : $52.00
  Discount      : 25.45%
  Stock         : 6.5 kg

=======================================================

  RESTOCK: Adding 10.0 kg of 'Onion (Loose)'

=======================================================

Restocked 10.0 kg successfully!

  ──────────────────────────────────────────────────
  Product       : Onion (Loose)
  Category      : Standard
  Original Price: $69.75
  Discount Price: $52.00
  Selling Price : $52.00
  Discount      : 25.45%
  Stock         : 16.5 kg

=======================================================

  OVERSELL ATTEMPT on 'Onion (Loose)'

=======================================================

Sale FAILED: tried to sell 116.5 kg but only 16.5 kg in stock.

=======================================================

  TOTAL INVENTORY VALUE: $292,089,469.75

=======================================================